name: First_GHA_Workflow
on: workflow_dispatch
jobs:
  first-job1:
     runs-on: ubuntu-latest
     steps:
         - name: Print Greeting
           run: echo "Hello world"
         - name: Print Goodbye
           run: |
             echo "This is my first GHA"
             echo "workflow excuted successfully"